server:
  port: 9000
spring:
  application:
    name: simply-consume-ribbon
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
#      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream