server:
  port: 9999
spring:
  application:
    name: uaa-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cloud-auth?cachePrepStmts=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: wokoworks
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/