server:
  port: 8000
spring:
  application:
    name: simply-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
#      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/