spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/niyiwei/spring-cloud-config-repo
      # 允许客户端覆盖属性
      override-none: true
  application:
    name: config-server
server:
  port: 4000
